export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum PaymentStatus {
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
}
export interface BaseBooking {
  id: string
  bookingId: string
  user_id: string
  salon_id: string
  salon_service_id: string
  worker_id: string
  workerName: string
  amount: number
  date: string
  time: string
  status: BookingStatus
  payment_id: string | null
  created_at: string
  duration: number
  serviceName: string
  paymentStatus: PaymentStatus
}

export interface Booking extends BaseBooking {
  customerName: string
  customerEmail: string
  customerPhone: string
}

export interface CustomerBooking extends BaseBooking {
  salonName: string
  salonLocation?: string
}

export interface TimeSlotResponse {
  salonId: string
  serviceId: string
  date: string
  isHoliday: boolean
  times: string[]
}

export interface SalonWorker {
  workerId: string
  name: string
  salonId: string
  services: Array<{
    serviceId: string
    salonId: string
    name: string
  }>
}

export interface WorkerSlot {
  serviceId: string
  date: string
  startTime: string
  duration: number
  buffer: number
  worker: SalonWorker
}

export interface AvailableWorkersResponse {
  slots: WorkerSlot[]
}

export interface PayHerePayload {
  sandbox: boolean
  merchant_id: string // PayHere Merchant ID
  return_url: string // URL to redirect users when success
  cancel_url: string // URL to redirect users when cancelled
  notify_url: string // URL to callback the status of the payment
  first_name: string // Customer’s First Name
  last_name: string // Customer’s Last Name
  email: string // Customer’s Email
  phone: string // Customer’s Phone No
  address: string // Customer’s Address Line1 + Line2
  city: string // Customer’s City
  country: string // Customer’s Country
  order_id: string // Order ID generated by the merchant
  items: string // Item title or Order/Invoice number
  currency: string // Currency Code (LKR/USD)
  amount: number // Total Payment Amount
  hash: string // Generated hash value
}
